version: "3.8"
services:
  cocorico:
    build:
      context: .
    ports:
      - 80:80
      - 3306:3306
      - 9001:9001
      - 27017:27017
    volumes:
      - ./../:/cocorico
    environment:
      - HOST_UID="${UID}"
    tty: true
    stdin_open: true
    command: /bin/bash
  mysql:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=cocorico
      - MYSQL_DATABASE=cocorico
      - MYSQL_USER=cocorico
      - MYSQL_PASSWORD=cocorico
    volumes:
      - ./../tmp/mysql:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_USERNAME: cocorico
      ADMINER_PASSWORD: cocorico
    depends_on:
      - cocorico
  mailcatcher:
    image: sj26/mailcatcher:latest
    ports:
      - "1080:1080"

