services:
    sonata.admin.contact:
        class: Cocorico\ContactBundle\Admin\ContactAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contact", label: "Messages" }
        arguments:
            - ~
            - Cocorico\ContactBundle\Entity\Contact
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]

    sonata.admin.contact_category:
        class: Cocorico\ContactBundle\Admin\ContactCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contact", label: "Category" }
        arguments:
            - ~
            - Cocorico\ContactBundle\Entity\ContactCategory
            - ~
        calls:
            - [ setTranslationDomain, [ SonataAdminBundle ] ]