services:
    #Messages subscriber
    cocorico_message.message.subscriber:
        class: Cocorico\MessageBundle\Event\MessageSubscriber
        arguments:
            - "@cocorico_message.mailer.twig_swift"
        tags:
            - { name: kernel.event_subscriber}