services:
    #Entities manager
    cocorico.listing_search.manager:
        class: Cocorico\CoreBundle\Model\Manager\ListingSearchManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
            - parameters:
                cocorico_booking_end_day_included: "%cocorico.booking.end_day_included%"
                cocorico_time_unit: "%cocorico.time_unit%"
                cocorico_listing_search_max_per_page: "%cocorico.listing_search_max_per_page%"
                cocorico_listing_availability_status: "%cocorico.listing_availability_status%"
        public: true

    cocorico.listing.manager:
        class: Cocorico\CoreBundle\Model\Manager\ListingManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
            - "%cocorico.listing_new_is_published%"
            - "%cocorico.dashboard_max_per_page%"
            - "@cocorico.mailer.twig_swift"

    cocorico.language.manager:
        class: Cocorico\CoreBundle\Model\Manager\LanguageManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "%cocorico.locales%"
        public: true

    cocorico.member_organization.manager:
        class: Cocorico\CoreBundle\Model\Manager\MemberOrganizationManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"