services:
    #Listing
    cocorico.form.handler.listing:
        class: Cocorico\CoreBundle\Form\Handler\Frontend\ListingFormHandler
        arguments:
        - "@security.token_storage"
        - "@security.authorization_checker"
        - "@request_stack"
        - "@cocorico.listing.manager"


