services:
    #Validators
    cocorico.listing_validator:
        class: Cocorico\CoreBundle\Validator\Constraints\ListingValidator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%cocorico.listing_img_max%"
            - "%cocorico.listing_img_min%"
            - "%cocorico.listing_category_min%"
            - "%cocorico.listing_price_min%"
            - "%cocorico.listing_countries%"
        tags:
            - { name: validator.constraint_validator, alias: listing }
