cocorico_user_frontend:
    resource: "@CocoricoUserBundle/Controller/"
    type:     annotation

cocorico_user_dashboard:
    resource: "@CocoricoUserBundle/Controller/Dashboard"
    type:     annotation
    prefix: /dashboard

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /%cocorico.admin%
    options: { i18n: false }

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

hwi_facebook_login:
    path: /oauth/fb-login
