services:
    #Forms
    cocorico_user.form.type.login:
        class: Cocorico\UserBundle\Form\Type\LoginFormType
        tags:
            - { name: form.type, alias: user_login }

    cocorico_user.form.type.register:
        class: Cocorico\UserBundle\Form\Type\RegistrationFormType
        arguments:
            - "%cocorico.time_unit%"
        tags:
            - { name: form.type, alias: user_registration }

    cocorico_user.form.type.contact:
        class: Cocorico\UserBundle\Form\Type\ProfileContactFormType
        arguments:
            - "%cocorico.time_unit%"
        tags:
            - { name: form.type, alias: user_address }

    cocorico_user.form.type.password_check:
        class: Cocorico\UserBundle\Form\Type\PasswordCheckFormType
        tags:
            - { name: form.type, alias: user_password_check }